<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net9.0</TargetFrameworks>
    <DisableFody>true</DisableFody>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <ProjectReference Include="..\BasicFodyAddin.Fody\BasicFodyAddin.Fody.csproj" />
    <ProjectReference Include="..\BasicFodyAddin\BasicFodyAddin.csproj" />
    <ProjectReference Include="..\AssemblyToProcess\AssemblyToProcess.csproj" />
  </ItemGroup>
</Project>
