image: Visual Studio 2022
skip_commits:
  message: /docs|Merge pull request.*/
build_script:
- ps: >-
    dotnet build BasicFodyAddin --configuration Release
test_script:
- pwsh: ./runTests.ps1
test: off
artifacts:
- path: nugets\*.nupkg